version: '3'

services:
  web:
    container_name: web
    image: jiho314518/humax16
    expose:
      - "8080"
    ports:
      - "3000:8080"
  redis:
    container_name: redis
    image: jiho314518/humax16_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
