version: '3'

services:
  redis:
    container_name: my-redis
    networks:
      - my-network
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
    container_name: web
    image: jiho314518/humax16
    expose:
      - "3000"
    ports:
      - "3000:8080"

networks:
  my-network:
    driver: bridge