version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    image: jiho314518/humax16
    expose:
      - "3000"
    ports:
      - "3000:3000"

  redis:
    container_name: my-redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"