version: '3'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=---------
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  web:
    container_name: web
    image: openjdk
    expose:
      - "8080"
    ports:
      - "60380:8080"
    environment:
      - TZ=Asia/Seoul
    command: "java -jar /build/libs/parking-0.0.1-SNAPSHOT.jar"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - TZ=Asia/Seoul