version: '3'

services:
  web:
    container_name: web
    image: jiho314518/humax16
    expose:
      - "3000"
    ports:
      - "3000:3000"
  redis:
    container_name: redis
    image: jiho314518/humax16_redis
    ports:
      - "6379:6379"
