spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.234.4.99:23306/dreambus16?serverTimezone=Asia/Seoul
    username: db16
    password: db12!@
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3ccff0e2c4b3aa00338b74edd8470a53
            client-secret: aygAFr2cweEu2wsrsaforgesDdilSlYI
            client-name: Kakao
            redirect-uri: http://localhost:8080/oauth/kakao/login
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  jpa:
    database:mysql
database-platform: org.hibernate.dialect.MySQL8Dialect
hibernate:
    ddl-auto: update
    properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
    org.hibernate.type.descriptor.sql: trace
    logging:
    level:
      root: debug
      session: store-type:jdbc
jwt:
  secretKey: bXktbmFtZS1pcy1ieWVvbmdpbC1oZWxsby1qd3QtaGFoYWhhLW15LW5hbWUtaXMtYnllb25naWwtaGVsbG8tand0LWhhaGFoYQ==
  blacklist:
    access-token: BlackList_AccessToken_
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
